import Home from '../components/home';
import bg from '../public/images/wather-backgroand.jpg'
import Countries from './../components/Countries';

export const  getStaticProps = async ()=> {
    const res = await fetch('http://api.weatherstack.com/current?access_key=1640ee92de401505fbf5c614c98c8de5&query=Yemen');
    const data = await res.json();
    return{
      props: {weathers: data}
    }
  }

  const Weather = ({weathers}) =>{
    
    return(
        <div  classNameName='body' style={{ backgroundImage: `url(${bg.src})`, }}>
            <h1>{weathers.current.is_day}</h1>
            <title>Wather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
        
      <div className="cointainer" >
        <div className="col-9" ><Home/></div>
        <div className="col-3"><Countries/></div>
      </div>
        </div>
    )
  }

  export default Weather